### ISSUE TITLE
Error loading AppIndicator on Ubuntu 16.04.2 LTS

### ISSUE THREAD

**Issue by minhazul-haque** [OzymandiasTheGreat/emoji-keyboard#1]
After installing all required packages via `apt` and `emoji-keyboard` using `pip3`, I got the following error,

```
minhaz@desktop > emoji-keyboard 
/usr/local/bin/emoji-keyboard:7: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk, GLib, AppIndicator3
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 890, in _find_spec
AttributeError: 'DynamicImporter' object has no attribute 'find_spec'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/emoji-keyboard", line 7, in <module>
    from gi.repository import Gtk, GLib, AppIndicator3
  File "/usr/lib/python3/dist-packages/gi/importer.py", line 127, in find_module
    'introspection typelib not found' % namespace)
ImportError: cannot import name AppIndicator3, introspection typelib not found
```

I had to install the following package to fix the error.

```bash
apt install gir1.2-appindicator3-0.1
```

Thanks.

**Comment by OpnSrcConstruction** [comment]
tried this on elementary loki  based on 16.04(installed from .deb file on releases page), and got the following results. Also the window wasn't resizable, and I also couldn't snap it to the edge. I could scroll through a line at a time, and beside the single line restriction the app worked perfectly. 

![emoji-keyboard_screenshot from 2017-03-30 21 51 30](https://cloud.githubusercontent.com/assets/6454764/24533144/ac57a4c0-1593-11e7-8cd5-57ed4ff17ae7.png)

**Comment by OzymandiasTheGreat** [comment]
Thank you and thank you! Your feedback is greatly appreciated.
@minhazul-haque Updated dependencies list.
@OpnSrcConstruction Hm, that's what I get for trusting gtk with window sizing.
I'll hard code window size in the next release. Should be out within a week, I'll update this bug then.

**Comment by OzymandiasTheGreat** [comment]
@OpnSrcConstruction Sorry for the delay. Hard-coded size in the new version. If that doesn't fix this, window is now resizable.
