### ISSUE TITLE
Switch keyboard focus when using the search function.

### ISSUE THREAD

**Issue by cfviotti** [OzymandiasTheGreat/emoji-keyboard#13]
I'm using keyboard shortcuts for both commands available. When opening the search box, it would be optimal if the keyboard focus switch to it automatically. As of now I need to click on the box and then start typing.
I'm on Ubuntu Gnome 17.04.

**Comment by OzymandiasTheGreat** [comment]
The search window should grab focus, if it doesn't it's most likely window manager preventing focus stealing. As I don't use Gnome I have no idea how to turn it off or even what's it called under Gnome.
Under Unity/Compiz it's called Focus Prevention Level, setting that to off ensures correct behavior.
I hope this gives you  a starting point for sorting this out.

**Comment by OzymandiasTheGreat** [comment]
So I've switched to Gnome and Gnome doesn't focus new windows at all.
Personally, I'm using [NoAnnoyance](https://extensions.gnome.org/extension/1236/noannoyance/) shell extension.
