### ISSUE TITLE
Can't install successfully

### ISSUE THREAD

**Issue by russellsilva** [OzymandiasTheGreat/emoji-keyboard#15]
I've tried installing from `pip3`, the official `deb` release, and the ppa and I can't get any of them to work. Here's what happens after installing the `.deb`. I've tried putting empty JSON files at `~/.config/emoji-keyboard.json` and `~/.local/share/recent_emoji.json` (which it complains about if `emoji-keyboard.json` exists) but then it just starts complaining that configuration keys are missing (correctly, since the files are just `{}`). What am I doing wrong here?

```
$ emoji-keyboard
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/emoji_keyboard/emoji_shared.py", line 33, in <module>
    with open(settings_file) as fd:
FileNotFoundError: [Errno 2] No such file or directory: '/home/rsilva/.config/emoji-keyboard.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/emoji-keyboard", line 5, in <module>
    from emoji_keyboard import emoji_shared as shared
  File "/usr/lib/python3/dist-packages/emoji_keyboard/emoji_shared.py", line 35, in <module>
    except (FileNotFoundError, json.decoder.JSONDecodeError):
AttributeError: 'module' object has no attribute 'JSONDecodeError'
````

**Comment by OzymandiasTheGreat** [comment]
`emoji-keyboard` is written on python 3.5 and that's what it requires, you seem to have an older python version.
Anyway, I've fixed  this particular error in the master branch, could you try installing with `pip3` again?
There's likely to be more bugs, but they're not hard to fix.

**Comment by russellsilva** [comment]
Thanks, it works now! I haven't seen any more showstopping bugs yet. 👍⬅ typed using emoji keyboard.

**Comment by OzymandiasTheGreat** [comment]
Great! If anything else pops up, let me know.
