### ISSUE TITLE
Feature Request:  Copy to clipboard

### ISSUE THREAD

**Issue by prg318** [OzymandiasTheGreat/emoji-keyboard#16]
As far as I can tell, it is impossible to use emoji-keyboard in a mouse-to-focus window manager, because the emoji picker window will take focus.

A workaround for this would be if there way a setting to click to copy to clipboard.  Would be great if there was a simple way to implement this

**Comment by OzymandiasTheGreat** [comment]
You can now choose to copy to clipboard in preferences in version 2.2.0
