### ISSUE TITLE
Should be installable in the user install directory

### ISSUE THREAD

**Issue by deuxpi** [OzymandiasTheGreat/emoji-keyboard#2]
Not all apps should require being installed globally on the system and require super-user privileges. It would be really useful to support installation in the user install directory, especially to try out the app. This is typically done by using the `--user` option of `pip install`.

What happens if I try to use `--user` option is that the install script still tries to copy files to global directories such as `/etc/` and fails:

```
$ pip3 install --user https://github.com/OzymandiasTheGreat/emoji-keyboard/archive/master.zip
    ...
    running install_data
    copying emoji-keyboard.desktop -> /home/ubuntu/.local/share/applications
    copying emoji-keyboard.desktop -> /etc/xdg/autostart
    error: could not create '/etc/xdg/autostart/emoji-keyboard.desktop': Permission denied
```

Otherwise, most of the installation is successful.

**Comment by OzymandiasTheGreat** [comment]
Thank you for your feedback.
Strange, on my system when using `--user` pip doesn't even try to access `/etc/`.
What version of `pip` are you using?
Anyway, I've disabled autostart for `--user` installs for now.
