### ISSUE TITLE
Start minimized

### ISSUE THREAD

**Issue by brpaz** [OzymandiasTheGreat/emoji-keyboard#21]
Hello.
On system startup, Emoji Keyboard always opens. That is annoying. I just want the indicator in the system tray.

**Comment by OzymandiasTheGreat** [comment]
emoji-keyboard should start minimized by default unless you launch it with `-k` flag.
Check startup applications / autorun .desktop file, there's probably `-k` flag in the exec line.

**Comment by brpaz** [comment]
Hmm, It seems I was using an older version of emoji-keyboard that I installed using the PPA. I removed it and installed the latest .deb file and it is fine now.

Thanks.
