### ISSUE TITLE
select custom emoji themes

### ISSUE THREAD

**Issue by rhetr** [OzymandiasTheGreat/emoji-keyboard#22]
I am mainly using this in conjunction with Signal Desktop so I'd like to be able to use the Signal theme.

**Comment by OzymandiasTheGreat** [comment]
Adding support / interface for custom themes would complicate the code even further and frankly it's already more complicated than I'd like. I'm just not willing to spend that much time on this.
Also, there aren't many themes to choose from to begin with.
If it's an open theme I can just include it in the next update, if it isn't you can replace one of the existing themes with it.
To do that find the installation directory (that depends on how you installed emoji-keyboard, for installations via pip: `~/.local/lib/python3.6/site-packages/emoji_keyboard` for user installs and `/usr/local/lib/python3.6/dist-packages/emoji_keyboard` for system installs), go into `data` dir, pick say `noto-emoji`, back up directory contents and place your files into it. The files must be svg and named after the unicode codepoint they represent, e.g. `1f0cf.svg` or `1f1e7-1f1ea.svg` for combining emoji.
