### ISSUE TITLE
Unable to launch emoji keyboard on Ubuntu 17.10

### ISSUE THREAD

**Issue by teras** [OzymandiasTheGreat/emoji-keyboard#23]
I have installed emoji keyboard through the PPA method.
Unfortunately this doesn't create any feedback.

When I run it from the command line I get the following error:

```
$ emoji-keyboard -s

** (emoji-keyboard:11319): WARNING **: Couldn't register with accessibility bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
Traceback (most recent call last):
  File "/usr/bin/emoji-keyboard", line 15, in <module>
    from emoji_keyboard import emoji_lib
ModuleNotFoundError: No module named 'emoji_keyboard'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/emoji-keyboard", line 17, in <module>
    from lib import emoji_lib
ModuleNotFoundError: No module named 'lib'
```

Any ideas?

**Comment by OzymandiasTheGreat** [comment]
That's a badly borked install, judging from the error you're missing most of the application files.
There might be an issue with the ppa version or there may have been errors during install, as I don't control the ppa there's not much I can do here.
Try reinstalling and if that doesn't work install from a different source.

**Comment by naught101** [comment]
@atareao, this is happening for me to. Looks like the current PPA version is broken.

**Comment by Jimeno0** [comment]
+1
