### ISSUE TITLE
Emoji 4.0/5.0 support?  

### ISSUE THREAD

**Issue by orsonteodoro** [OzymandiasTheGreat/emoji-keyboard#25]
I am using 2.3.0 and I cannot find any emojis in Emoji 4.0 (https://emojipedia.org/emoji-4.0/) and Emoji 5.0 (https://emojipedia.org/emoji-5.0/).  I can find the technologist, the ufo, sauropod.

**Comment by OzymandiasTheGreat** [comment]
Emoji support is fully dependent on emoji support in the selected set and emoji.json database I take from emojitwo project. If there are no images for the emoji in the set there's nothing to display, so until the sets are updated to support latest emoji emoji-keyboard won't support them as well.

**Comment by ffxsam** [comment]
@OzymandiasTheGreat Why EmojiTwo instead of EmojiOne? I realize it's now a licensed product, but it should be free for your purposes: https://www.emojione.com/licenses

And it's kept up to date, unlike EmojiTwo.

**Comment by OzymandiasTheGreat** [comment]
I'm not touching anything that's not open source, that's why.

**Comment by OzymandiasTheGreat** [comment]
That's the first time I'm hearing this. Tapping into that would be lovely and simple I hope.
Mind dropping a link so I could look into this further?

**Comment by ffxsam** [comment]
Yep, look at this gloriousness!

![image](https://user-images.githubusercontent.com/12532733/39085516-26c82bae-4549-11e8-8e5b-2083d49e5f9e.png)

Info:
https://www.omgubuntu.co.uk/2017/08/color-emoji-support-coming-gnome-desktop
https://www.omgubuntu.co.uk/2017/11/ubuntu-finally-long-last-time-support-color-emoji

**Comment by ffxsam** [comment]
So, technically you can use the Characters application to copy/paste emoji, but it's not nearly as elegant as emoji-keyboard.

**Comment by OzymandiasTheGreat** [comment]
Oh, I forgot about those articles. According to them, Ubuntu will use Noto emoji set. That's already an option with emoji keyboard.
Alas, not all emoji may be available for now, because the data file I use comes from emojitwo.
Only emojitwo provides a data (json) file with all required info, and compiling my own is more work than I'm willing to do.

**Comment by OzymandiasTheGreat** [comment]
I don't think ubuntu will have a repository of emoji data, just the font and latest gnome version that can actually display the font. So tapping into that is not an option.

**Comment by ffxsam** [comment]
Ahh, bummer. It was worth a shot!

**Comment by gadicc** [comment]
Does this help?  [emoji.json](https://www.npmjs.com/package/emoji.json) on npm.

MIT licensed, just converts all the data from the [Unicode emoji list](https://unicode.org/emoji/charts/emoji-list.html) to JSON.  Currently at Emoji 11.0 :D

```js
var emoji = require('emoji.json')
console.log(emoji[2])
// {
//   no: 3,
//   codes: '1F602',
//   char: '😂',
//   name: 'face with tears of joy',
//   keywords: 'face | face with tears of joy | joy | laugh | tear'
// }
```

**Comment by gadicc** [comment]
Oh, it maybe doesn't have the short names you're looking for (e.g. `:joy:`).  To compare:

In [EmojiTwo](https://github.com/EmojiTwo/emojitwo/blob/master/emoji.json):

```js
{
	"code_points": {
		"base": "1f602",
		"non_fully_qualified": "1f602",
		"decimal": "&#128514;"
	},
	"name": "face with tears of joy",
	"shortname": ":joy:",
	"category": "people",
	"emoji_order": "3",
	"shortname_alternates": [],
	"ascii": [":')", ":'-)"],
	"keywords": ["happy", "silly", "smiley", "cry", "laugh", "emotion", "sarcastic"]
}
```

I found another alternative though, [emoji-data](https://github.com/iamcal/emoji-data) (also MIT licensed), which has an `emoji.json` (and [emoji-pretty.json](https://raw.githubusercontent.com/iamcal/emoji-data/master/emoji_pretty.json)) with entries like this:

```js
{
        "name": "FACE WITH TEARS OF JOY",
        "unified": "1F602",
        "non_qualified": null,
        "docomo": "E72A",
        "au": "EB64",
        "softbank": "E412",
        "google": "FE334",
        "image": "1f602.png",
        "sheet_x": 30,
        "sheet_y": 26,
        "short_name": "joy",
        "short_names": [
            "joy"
        ],
        "text": null,
        "texts": null,
        "category": "Smileys & People",
        "sort_order": 3,
        "added_in": "6.0",
        "has_img_apple": true,
        "has_img_google": true,
        "has_img_twitter": true,
        "has_img_facebook": true,
        "has_img_messenger": true
}
```
Unclear what Unicode Emoji version it's at, but definitely later than the current.

**Comment by OzymandiasTheGreat** [comment]
New version out, includes *ALL* the emoji! In case there's an image missing in your selected set, it will be displayed as black and white symbol from the system font.
I'm finally closing this.

**Comment by gadicc** [comment]
Ahhh amazing newsssss... thanks @OzymandiasTheGreat!! :D :D
