### ISSUE TITLE
Systemd build time dependence

### ISSUE THREAD

**Issue by orsonteodoro** [OzymandiasTheGreat/emoji-keyboard#26]
Your Wayland support needs systemd as a build time dependence and I only use OpenRC.  Consider removing references or adding more checks in lib/emoji_shared.py to systemd apps for loginctl.  I am not using Wayland but X11, and I cannot install if I remove the check_wayland() function.  I don't think it is necessary to install systemd for Wayland.

**Comment by OzymandiasTheGreat** [comment]
I am yet to find a more reliable way to detect wayland than loginctl, so can't do much about that for now.
On the other hand requiring loginctl at build time is completely unnecessary and will be fixed when I get some free time.

**Comment by OzymandiasTheGreat** [comment]
New version out, no explicit systemd dependencies, no installation.
It's an electron app distributed as an AppImage, please check it out.
I'm closing this, since it's no longer applicable.
