### ISSUE TITLE
[Feature request] Close window on Escape

### ISSUE THREAD

**Issue by erikw** [OzymandiasTheGreat/emoji-keyboard#27]
It would be very convenient if the main floating window would close when pressing the escape key :).

**Comment by OzymandiasTheGreat** [comment]
Yeah, that would be nice. Will do.

**Comment by mehmetakiftutuncu** [comment]
I would also love to be able to navigate through the picker with keyboard. I assigned a global shortcut to launch it but it's hard to stop and select an emoji with mouse in the middle of my typing.

**Comment by OzymandiasTheGreat** [comment]
@mehmetakiftutuncu That's what the search function is for. Implementing keyboard navigation would be a major rewrite/redesign. Currently the main picker window actively refuses keyboard focus and that allows "typing" emoji straight into focused application.

**Comment by mehmetakiftutuncu** [comment]
@OzymandiasTheGreat Pressing a few arrow keys to pick my emoji is way easier than having to remember its name and search for it every time. You already interrupt typing to input emoji when you have a dedicated keyboard shortcut launching emoji keyboard. So, emoji keyboard can capture keyboard focus at that point. I don't see a problem with that.

**Comment by OzymandiasTheGreat** [comment]
You're missing the point. Typing of emoji won't work if keyboard focus is captured.
And using arrow keys to go through the myriad of emoji available sounds like hell.
Sorry, but this is not a good idea and I am not going to implement it.

**Comment by OzymandiasTheGreat** [comment]
So, the closing with escape key is not implemented yet, but will be soonish.
I've been busy and then I rewrote the whole app and forgot to include this...
Also I went back on my word and implemented keyboard navigation in the app.
Do please check out the new version!

**Comment by OzymandiasTheGreat** [comment]
Ok, I'm sorry this took so long, but it is DONE now. Check out the latest release.
