### ISSUE TITLE
`check_wayland()` fails when running as root

### ISSUE THREAD

**Issue by raabf** [OzymandiasTheGreat/emoji-keyboard#28]
The command

      sudo python3 setup.py install

or 

      sudo pip3 install https://github.com/OzymandiasTheGreat/emoji-keyboard/archive/master.zip

fails with

       Traceback (most recent call last):
         File "setup.py", line 5, in <module>
           from lib.emoji_shared import version
         File "/media/coss/git/emoji-keyboard/lib/emoji_shared.py", line 102, in <module>
           wayland = check_wayland()
         File "/media/coss/git/emoji-keyboard/lib/emoji_shared.py", line 87, in check_wayland
           ['loginctl', 'show-session', session, '-p', 'Type', '--value'],
       UnboundLocalError: local variable 'session' referenced before assignment

The reason is that in 
https://github.com/OzymandiasTheGreat/emoji-keyboard/blob/88af90475b55d0202fb38100a7d27b0d6d692d23/lib/emoji_shared.py#L78-L82

`sessions` hold the current logged in user:

        SESSION        UID        USER            SEAT            
        1             1000      raabf            seat0

however `os.getenv('USER')` returns `root` since its called with sudo and hence `session` is empty.

**Environment**
  - Ubuntu 16.04
  - XServer
  - Python 3.5.2

**Comment by OzymandiasTheGreat** [comment]
And fixed. I forgot to push that one, sorry 'bout that.

**Comment by raabf** [comment]
great! it works now.
