### ISSUE TITLE
Installation failed: Failed to list sessions: Access denied

### ISSUE THREAD

**Issue by believer-ufa** [OzymandiasTheGreat/emoji-keyboard#30]
```
Traceback (most recent call last):
  File "setup.py", line 5, in <module>
    from lib.emoji_shared import version
  File "/home/roman/pkg/must-update/emoji-keyboard-git/src/emoji-keyboard/lib/emoji_shared.py", line 100, in <module>
    wayland = check_wayland()
  File "/home/roman/pkg/must-update/emoji-keyboard-git/src/emoji-keyboard/lib/emoji_shared.py", line 85, in check_wayland
    ['loginctl', 'show-session', session, '-p', 'Type'],
UnboundLocalError: local variable 'session' referenced before assignment
```

My environment: Arch linux, Xorg, KDE.

Please can you tell me why it throwing an error? Is error on that line:

https://github.com/OzymandiasTheGreat/emoji-keyboard/blob/ac9b75f7ee57e13412257d108078da896f29944c/lib/emoji_shared.py#L80

**Comment by believer-ufa** [comment]
as i see, it getting error on running command `loginctl', 'list-sessions`. It working fine if i running it from my terminal.

```bash
loginctl list-sessions
   SESSION        UID USER             SEAT             TTY             
        c2       1000 roman            seat0                            

1 sessions listed.
```

**Comment by ameketa** [comment]
The specific issue here is not permissions; it's that the PR in #29 changed the implementation from `os.getlogin()` to `getpass.getuser()`. However, these differ in their behavior under sudo:

```python
# test.py
import os
import getpass

print(os.getlogin())
print(getpass.getuser())
```

```
$ python3 test.py
user
user
$ sudo python3 test.py
user
root
```
The new implementation comes back with `root` under sudo, which then doesn't match any of the output of loginctl list-sessions, which then fails to set the variable `session`, which then blows things up when it tries to reference that variable.

**Comment by OzymandiasTheGreat** [comment]
@ameketa Thanks for tracking this down, I just pushed a fix for this.

**Comment by ameketa** [comment]
@OzymandiasTheGreat :tada: that fixed it, thanks! I think this issue can be closed.
