### ISSUE TITLE
[Feature request] Merge search box & keyboard in one

### ISSUE THREAD

**Issue by ffxsam** [OzymandiasTheGreat/emoji-keyboard#33]
It would be nice to integrate the search box in the same popup as the keyboard itself. That way we can easily just search, or choose something from recents.

**Comment by OzymandiasTheGreat** [comment]
Considering how different the functionality and implementation of the search and the palette windows is, this would be way more work than I'm willing to put into this. And I'm pretty sure the end result would be unsatisfactory as well.
So no.

**Comment by OzymandiasTheGreat** [comment]
Aaand it's done. New version, rewritten in electron is out and did consider this when (re)designing it.
Please check it out, I'm closing this.
