### ISSUE TITLE
Cannot install using pip when not in login shell

### ISSUE THREAD

**Issue by tkedwards** [OzymandiasTheGreat/emoji-keyboard#41]
I use a cron job to install packages across several machines. When I try to install emoji-keyboard using pip3 in the cron job, i.e without being in an 'interactive' session, it fails:
```
Collecting https://github.com/OzymandiasTheGreat/emoji-keyboard/archive/master.zip
  Downloading https://github.com/OzymandiasTheGreat/emoji-keyboard/archive/master.zip
    Complete output from command python setup.py egg_info:
    Unable to init server: Could not connect: Connection refused
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-avx08ieq-build/setup.py", line 5, in <module>
        from lib.emoji_shared import version
      File "/tmp/pip-avx08ieq-build/lib/emoji_shared.py", line 102, in <module>
        wayland = check_wayland()
      File "/tmp/pip-avx08ieq-build/lib/emoji_shared.py", line 82, in check_wayland
        current_user = current_user if current_user != 'root' else os.getlogin()
    OSError: [Errno 25] Inappropriate ioctl for device
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-avx08ieq-build/
Calibre is up-to-date

```

I had a look at the code, and it seems like the code in check_wayland() and get_keycode() is the problem. This code looks like it should be run at runtime (i.e when the user is starting emoji-keyboard in their desktop session), but there should be no reason to run it at install time during a 'pip install' as far as I understand it.

**Comment by auryn-macmillan** [comment]
I had a similar issue, the solution ended up being to run `pip3 install` command without sudo.

**Comment by OzymandiasTheGreat** [comment]
New version out, no installation needed anymore, since it's an AppImage.
Please use that from now on.
