### ISSUE TITLE
Can't dismiss search window without picking an emoji

### ISSUE THREAD

**Issue by mahmoudhossam** [OzymandiasTheGreat/emoji-keyboard#42]
Sometimes I want to dismiss the search window instead of selecting an emoji.

I tried pressing the ESC key but that doesn't work and I have to close it using my i3 keybinding for close, is there something I'm doing wrong or does this need to be added?

**Comment by OzymandiasTheGreat** [comment]
This needs to be added.
There's a new version out, but I haven't yet implemented window closing through escape key.

**Comment by OzymandiasTheGreat** [comment]
Closing with `Escape` is now done. Check out 3.1.0 in the releases.
