### ISSUE TITLE
Focus search text field when opening `emoji-keyboard -s`

### ISSUE THREAD

**Issue by dergigi** [OzymandiasTheGreat/emoji-keyboard#43]
Would be great if the search text field would have focus by default. As it is now, I have to press my shortcut to bring up the keyboard and then use the mouse to click in the search field.

**Comment by cemulate** [comment]
This is a major problem for me too. It's not even possible to alt-tab to the window since it doesn't appear in the alt-tab list.

**Comment by OzymandiasTheGreat** [comment]
New version out, this is "fixed".
Scare-quotes, because it's rewritten in electron and described behavior is now implemented.
Just one thing, command line switches are currently not supported. You launch search by pressing
`Ctrl+Super+F`.
