### ISSUE TITLE
 [Feature request] Mouswheel scrolling and Blobmoji

### ISSUE THREAD

**Issue by BunnyTheLifeguard** [OzymandiasTheGreat/emoji-keyboard#44]
Hey, great job with the keyboard. Working good so far on Manjaro via the AUR package.
Can you implement scrolling via mousewheel and [Blobmojis](https://github.com/c1710/blobmoji)?

Thanks in advance :)

**Comment by BunnyTheLifeguard** [comment]
😟

**Comment by OzymandiasTheGreat** [comment]
So good news, I'm working on new version and it will have blobmoji.
Possibly bad news - it's based on electron, because I'm done working around gtk bugs.

**Comment by BunnyTheLifeguard** [comment]
Sounds good.
Using KDE anyway, should be fine I guess!? 🤔😅

**Comment by OzymandiasTheGreat** [comment]
New version is out and it has BLOBMOJI!
By the way, it's strange that you couldn't scroll through mouse wheel. Must've been another gtk bug.
I'm closing this, since both requests are implemented now.
