### ISSUE TITLE
Recent Tab stays empty

### ISSUE THREAD

**Issue by tbrodbeck** [OzymandiasTheGreat/emoji-keyboard#45]
Hey! Great application :) But unfortunately the recent tab stays empty no matter how often I select an emoji.
```
Version:
emoji-keyboard 2.2.0-2
inxi -F:
CPU: Dual Core Intel Core i5-3210M (-MT MCP-) speed/min/max: 1197/1200/3100 MHz 
Kernel: 4.19.56-1-MANJARO x86_64 Up: 1d 20h 38m Mem: 3207.5/7850.8 MiB (40.9%) 
Storage: 113.00 GiB (68.0% used) Procs: 228 Shell: zsh 5.7.1 inxi: 3.0.35 
```

**Comment by OzymandiasTheGreat** [comment]
Please try the new version, it's a major rewrite, but recent handling code is pretty similar.
Could you check and see if the issue persists?

**Comment by tbrodbeck** [comment]
Sorry I cannot. I switched back to macOS from Linux in the meantime.

**Comment by OzymandiasTheGreat** [comment]
Oh that's unfortunate :wink: 
I'm closing this.
