### ISSUE TITLE
Window keeps getting slightly moved down after each opening/closing

### ISSUE THREAD

**Issue by ccxex29** [OzymandiasTheGreat/emoji-keyboard#46]
Onboard Emoji Keyboard keeps getting moved down after each opening/closing of the window. The window state is slightly modified which I believe shouldn't be the intended behavior.

To replicate, just keep switching the keyboard state open and close via tray or `emoji-keyboard -k`

System:
Distro : Manjaro Linux 18.1.0
Kernel : Linux 5.3.5-1-MANJARO x86_64
DE/WM : Xfce 4.14.1/Xfwm 4.14.0git.5ea89c

**Comment by OzymandiasTheGreat** [comment]
New version is written in electron, no more gtk bugs.
