### ISSUE TITLE
[question] Is the project dead?

### ISSUE THREAD

**Issue by kirk86** [OzymandiasTheGreat/emoji-keyboard#47]
I was wondering if the project is dead since the last update seems to be two years ago?

**Comment by OzymandiasTheGreat** [comment]
Not anymore!
I have been *busy* with work and studies, and have pretty much forgotten about this project.
Not anymore! Sorry 'bout that.
There's a new version, rewritten in electron for easier maintainability.
Do check it out, feedback is always welcome!
