### ISSUE TITLE
Add option to choose emoji icon set

### ISSUE THREAD

**Issue by dpdani** [OzymandiasTheGreat/emoji-keyboard#5]
Often people have a tendency to prefer one icon set rather than others for no specific reason. For instance, I never bought an Apple phone, but the Apple icon set is my favorite.
I think that since there's no standardization in the Linux ecosystem around any of the available icon sets, it would be a good idea to leave the option to the end-user.

Icon sets recognized by the Unicode Consortium are shown [here](http://unicode.org/emoji/charts/full-emoji-list.html).

**Comment by OzymandiasTheGreat** [comment]
@dpdani as far as I'm aware the only color emoji sets available for linux under an open licence are emoji one and twitter's emoji. So these are the only ones I could include legally.
And 'could' doesn't mean 'will'. At this point typed emoji most likely won't match emoji displayed in the app.
Until that changes, I don't see a point in implementing this choice.

**Comment by Phidica** [comment]
I'd like to voice my support for @dpdani's suggestion. As a heavy Discord user I have become accustomed to the look of the Twemoji set and prefer it over EmojiOne. I would like if switching between at least these two sets was possible in the program, as it is easier to choose an emoji from the panel when their appearance is what you are used to

You say "typed emoji most likely won't match emoji displayed in the app" which is true, however this is true whether the emoji in the app are EmojiOne or Twemoji, so I don't quite see how that should affect the decision to implement this customisation or not

**Comment by OzymandiasTheGreat** [comment]
Added Twitter emoji and Noto emoji sets in version 2.2.0.
