### ISSUE TITLE
Application doesn't launch

### ISSUE THREAD

**Issue by nkenschaft** [OzymandiasTheGreat/emoji-keyboard#66]
I am currently trying to run the application via AppImage on Arch Linux, but it simply does not launch. There is no error outputted, and python.log is empty. The only output given is a warning about a deprecated default variable in electron.

**Comment by pm0u** [comment]
same here. killing the process with ctrl+c produces a pop up with the error in #65 

otherwise, I only get the output:

```
(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
```

**Comment by rbreaves** [comment]
Same, even a debian repo I found with it fails to run too. To be honest.. I feel like an electron app for emoji's is a bit heavy, but certainly easier to get up an running for a prototype - at least you would think. Not something I would want to run on low powered devices with limited memory or cpu resources though.

```
(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
```

**Comment by rbreaves** [comment]
It appears like it started to work later despite that error message, go figure. Kinda slow to load up and doesn't go away after selecting what I want and cannot be quickly navigated by keyboard. Limitations of electron I am sure.

**Comment by klarkc** [comment]
Me too on Arch linux:

```
[klarkc@ssdarch ~]$ emoji-keyboard 
This doesn't look like a squashfs image.

Cannot mount AppImage, please check your FUSE setup.
You might still be able to extract the contents of this AppImage 
if you run it with the --appimage-extract option. 
See https://github.com/AppImage/AppImageKit/wiki/FUSE 
for more information
```

**Comment by jordi-pujol** [comment]
@klarkc
read carefully the message where it says:

"run it with the --appimage-extract option."

**Comment by ViktorWalter** [comment]
Seconded.
Ubuntu 20.04, 5.10.0-051000-generic

**Comment by ViktorWalter** [comment]
Ok, update. I **can** get my own compiled appimage running, **if** I do 
```
python3 -m venv .venv
source .venv/bin/activate
poetry install
```
beforehand. I think the appimage might be missing some of the dependencies inside.

**Comment by rpardee** [comment]
@ViktorWalter I'm guessing you run those commands in the dir of your local clone of the repository?

**Comment by rpardee** [comment]
I wasn't able to get those build-from-source directions to work, but eventually realized that the program *was* starting.  It just doesn't pop the emoji-picker right away--it adds a little poop icon in the extreme upper-right of the screen that  you can click to pop that UI:
![image](https://user-images.githubusercontent.com/26327/149677975-667d8117-9c5a-461c-8d66-a25f89005be3.png)

**Comment by mrtztg** [comment]
> I wasn't able to get those build-from-source directions to work, but eventually realized that the program _was_ starting. It just doesn't pop the emoji-picker right away--it adds a little poop icon in the extreme upper-right of the screen that you can click to pop that UI: ![image](https://user-images.githubusercontent.com/26327/149677975-667d8117-9c5a-461c-8d66-a25f89005be3.png)

I agree with you. But when I click on some of the emojis, I face with error again.

**Comment by ViktorWalter** [comment]
> @ViktorWalter I'm guessing you run those commands in the dir of your local clone of the repository?

Yes.

**Comment by OzymandiasTheGreat** [comment]
Please try the new version, as it no longer uses electron or python, this should be irrelevant.
