### ISSUE TITLE
This app does not start up.  JavaScript error in the main process.

### ISSUE THREAD

**Issue by jeremymreed** [OzymandiasTheGreat/emoji-keyboard#67]
I'm getting this error when starting this application.

The error is a JavaScript error occurring in the main process.

![Here is the stack trace](https://user-images.githubusercontent.com/32230660/171689727-1ecb51b7-6eef-4acb-87a3-4c091a6b7bdd.png)

**Comment by vinivosh** [comment]
Been getting this too when I run the application. But I also get this error right after: 

<img width="429" alt="image" src="https://user-images.githubusercontent.com/36175157/189500126-9e398318-ef32-4bc2-88d4-b1e4581a72ff.png">

Same error happens again whenever I try clicking an emoji in the picker.

**Comment by BradB58** [comment]
I'm getting the same errors after upgrading from Linux Mint 20.3 to 21. Using Appimage 3.1.1. Worked perfectly on Linux Mint 20.3.

**Comment by vinivosh** [comment]
[This fork here](https://github.com/edam/emoji-keyboard) worked normally, so something there fixed it (or didn't mess it up in the first place? Idk)

**Comment by OzymandiasTheGreat** [comment]
Please try the new version, as it no longer uses Electron, this should be irrelevant.
