### ISSUE TITLE
Include U+20BF (Bitcoin Sign)

### ISSUE THREAD

**Issue by GraoMelo** [OzymandiasTheGreat/emoji-keyboard#68]
Dear developers,

could you add currency symbols:

Unicode: 

![btc-crrnc](https://user-images.githubusercontent.com/60477737/188610282-d8f66dfc-32b3-4154-8418-a7542cd3c893.png)

### Bitcoin Sign

| Name | Number |
| ------ | ------ |
| Number Unicode | U+20BF |
| ------ | ------ |
| HTML Code | : '&#8383'; |
| ------ | ------ |
| CSS code: | '\20BF' | 

<p>Unicode version 10: https://www.unicode.org/charts/PDF/Unicode-10.0/U100-20A0.pdf
<p>General information: https://util.unicode.org/UnicodeJsps/character.jsp?a=20BF
<p>Technical information: https://www.unicode.org/L2/L2015/15229-bitcoin-sign.pdf

**Comment by OzymandiasTheGreat** [comment]
I purposely chose not to directly control what's included. I depend on third party package to provide the data based on adoption in the wild. It also depends on what symbols are supported by the system font installed. So I'm closing this as it's out of scope.
