### ISSUE TITLE
Emojis are huge on a HiDPI desktop

### ISSUE THREAD

**Issue by arty-name** [OzymandiasTheGreat/emoji-keyboard#7]
I have a HiDPI screen, and the keyboard is rather inconvenient on it, having only two rows of huge emojis: 
![image](https://cloud.githubusercontent.com/assets/133055/26393351/e127242c-4069-11e7-8b98-9e82a5c61adf.png)

From the other screenshots I see 4 rows of emojis on screens with normal resolution.

**Comment by OzymandiasTheGreat** [comment]
Which version are you using? In version 2.0 you can change emoji size in the preferences dialog (needs restart).

**Comment by arty-name** [comment]
The one in the PPA

**Comment by OzymandiasTheGreat** [comment]
The PPA is not maintained by me and it's outdated. You can download latest version (2.1.0) from releases here on github.

**Comment by arty-name** [comment]
I don’t know how I missed that part in the Readme. Sorry for bothering you, I will try to install the newer version.

**Comment by OzymandiasTheGreat** [comment]
No problem, if you have any issues with the latest version do report them here. You feedback is greatly appreciated!

**Comment by arty-name** [comment]
Ironically this setting of icon size doesn’t seem to work for me. I have tried increasing it to 64 and after the restart it is 32 again.

**Comment by OzymandiasTheGreat** [comment]
Strange, works fine on my test machine. Could you run it from a terminal, change emoji size, exit and start it from the terminal again. See if it throws up any errors?

**Comment by arty-name** [comment]
It doesn’t throw any errors, but I have noticed that it saves the value on blur. If I type 64 and press Tab, the value is saved after restart. However when I type 64, do not remove the cursor from the input, close the settings window and restart the keyboard, it keeps the old value.

**Comment by OzymandiasTheGreat** [comment]
Ah, managed to reproduce it. It's a Gtk+ quirk, it does not save the value if the focus does not change, not much I can do about it I'm afraid.

**Comment by arty-name** [comment]
It’s not too bad :)
