### ISSUE TITLE
Low-res emoji on HiDPI screens

### ISSUE THREAD

**Issue by arty-name** [OzymandiasTheGreat/emoji-keyboard#8]
I have a HiDPI screen, and the emoji in the virtual keyboard seem blurry, as happens when low-resolution resources are used:
![bildschirmfoto vom 2017-05-24 23-39-22](https://cloud.githubusercontent.com/assets/133055/26426872/c143ac90-40da-11e7-83a4-c9dfb9b2f9d8.png)

Changing the size in settings only increases the emojis in size, but they remain blurry. It would be nice to see them in high resolution.

**Comment by OzymandiasTheGreat** [comment]
The emojis are in svg format, so they should be sharp at any resolution, in theory at least. I'm only guessing here, but I think Gtk+ rasterizes emoji when loading and then upscales them for HiDPI. Again, this is a Gtk+ quirk and there's not much I can do about it.

**Comment by arty-name** [comment]
I think there should be a way, since most of other Gtk apps have sharp icons

**Comment by OzymandiasTheGreat** [comment]
New version out, doesn't depend on gtk at all now. It's an electron app distributed as an AppImage.
Could you please try the new version and see if the issue persists?

**Comment by arty-name** [comment]
The issue is resolved, thanks!
